### ISSUE TITLE
arcolinux-mirrorlist

### ISSUE THREAD

**Issue by LomigLavnek** [arcolinuxb/arco-gnome#1]
Hi,

when building gnome image, everything's ok with 30-build-the-iso-local-v3.sh but when the script launches the build.sh script, I get the following error : 
`➜  archiso sudo ./build.sh -v
###################################################################
2. Base installation, plus needed packages (airootfs)
###################################################################

[mkarchiso] INFO: Configuration settings
[mkarchiso] INFO:                   Command:   init
[mkarchiso] INFO:              Architecture:   x86_64
[mkarchiso] INFO:         Working directory:   work/x86_64
[mkarchiso] INFO:    Installation directory:   arch
[mkarchiso] INFO:        Pacman config file:   work/pacman.conf

[mkarchiso] INFO: Installing packages to 'work/x86_64/airootfs/'...
==> Creating install root at work/x86_64/airootfs
==> Installing packages to work/x86_64/airootfs
error: config file /etc/pacman.d/arcolinux-mirrorlist could not be read: No such file or directory
==> ERROR: Failed to install packages to new root
`

I don't know where I can get the arcolinux-mirrorlist file.

Thanks

**Comment by arcolinuxz** [comment]
Check the forum and arcolinux.com for the info.
It is ofcourse there for you.

CheerS
Erik
